service: travel-journal-s3-bucket

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

custom:
  s3BucketNames:
    dev: dev-travel-journal-assets
    stg: stg-travel-journal-assets
    prod: travel-journal-assets

resources:
  Resources:
    # s3 resources bucket
    TravelJournalBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketNames.${self:provider.stage}}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
              ExposedHeaders:
                - last-modified
                - content-length
                - etag
                - x-amz-version-id
                - content-type
                - x-amz-request-id
                - x-amz-id-2
                - date
                - x-amz-cf-id
                - x-amz-storage-class
                - access-control-expose-headers
              MaxAge: 3000

    TravelJournalBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref TravelJournalBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "${TravelJournalBucket}/*"

  Outputs:
    S3BucketName:
      Description: "Name of the S3 bucket"
      Value: ${self:custom.s3BucketNames.${self:provider.stage}}
