// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file images/user_images.proto (package prototypes, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file images/user_images.proto.
 */
export const file_images_user_images: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChhpbWFnZXMvdXNlcl9pbWFnZXMucHJvdG8SCnByb3RvdHlwZXMiaQoPUHJvdG9Vc2VySW1hZ2VzEgoKAlBLGAEgASgJEgoKAlNLGAIgASgJEhAKCGltYWdlX2lkGAMgASgJEhEKCWltYWdlX3VybBgEIAEoCRIZChFpbWFnZV9kZXNjcmlwdGlvbhgFIAEoCUIHWgUvbG9nc2IGcHJvdG8z"
  );

/**
 * Represents a user entity
 *
 * @generated from message prototypes.ProtoUserImages
 */
export type ProtoUserImages = Message<"prototypes.ProtoUserImages"> & {
  /**
   * @generated from field: string PK = 1;
   */
  PK: string;

  /**
   * @generated from field: string SK = 2;
   */
  SK: string;

  /**
   * @generated from field: string image_id = 3;
   */
  imageId: string;

  /**
   * @generated from field: string image_url = 4;
   */
  imageUrl: string;

  /**
   * @generated from field: string image_description = 5;
   */
  imageDescription: string;
};

/**
 * Describes the message prototypes.ProtoUserImages.
 * Use `create(ProtoUserImagesSchema)` to create a new message.
 */
export const ProtoUserImagesSchema: GenMessage<ProtoUserImages> =
  /*@__PURE__*/
  messageDesc(file_images_user_images, 0);
