service: travel-journal-cognito-auth

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    CognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
        Schema:
          - AttributeDataType: String
            Name: email
            Required: true
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false

    CognitoUserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
          - USER_PASSWORD_AUTH
        GenerateSecret: false

  Outputs:
    CognitoArn:
      Description: "Cognito ARN"
      Value:
        Fn::GetAtt:
          - CognitoUserPool
          - Arn

    CognitoUserPoolArn:
      Description: "Cognito User Pool ARN"
      Value:
        Fn::GetAtt:
          - CognitoUserPool
          - Arn
