// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file users/users.proto (package prototypes, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file users/users.proto.
 */
export const file_users_users: GenFile = /*@__PURE__*/
  fileDesc("ChF1c2Vycy91c2Vycy5wcm90bxIKcHJvdG90eXBlcyJSCglQcm90b1VzZXISDQoFZW1haWwYASABKAkSDAoEbmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCRIKCgJQSxgEIAEoCRIKCgJTSxgFIAEoCUIHWgUvbG9nc2IGcHJvdG8z");

/**
 * Represents a user entity
 *
 * @generated from message prototypes.ProtoUser
 */
export type ProtoUser = Message<"prototypes.ProtoUser"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * @generated from field: string PK = 4;
   */
  PK: string;

  /**
   * @generated from field: string SK = 5;
   */
  SK: string;
};

/**
 * Describes the message prototypes.ProtoUser.
 * Use `create(ProtoUserSchema)` to create a new message.
 */
export const ProtoUserSchema: GenMessage<ProtoUser> = /*@__PURE__*/
  messageDesc(file_users_users, 0);

